# title of website
title: nav

# description of website
description: gsyx666's navigation site

# favicon of website
favicon: "https://github.com/gsyx666.png?size=40"

# your website url
url: https://gsyx666.github.io/gena/

# github profile url
github: "https://github.com/gsyx666"

# footer message
footer: © 2021-2021 @gsyx666

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
# google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: true
    default: baidu
    # 可选的搜索引擎
    engines:
      - google
      - github
      - weibo
      - baidu
      - bilibili
      - zhihu

content:
  categories:
    - name: 常用推荐
      sites:
        - name: github
          description: github
          url: https://github.com/
        - name: 哔哩哔哩
          description: bilibili
          url: https://www.bilibili.com/
        - name: 玩安卓
          description: 每日推荐安卓优质文章
          url: https://www.wanandroid.com/
        - name: 安卓开发者
          description: 安卓开发者官网
          url: https://developer.android.google.cn/index.html
        - name: 吾爱破解
          description: 吾爱破解 - LCG - LSG|安卓破解|病毒分析|
          url: https://www.52pojie.cn/
        - name: 看雪论坛
          description: 安全社区
          url: https://bbs.pediy.com/
        - name: MT论坛
          description: Android 逆向论坛
          url: https://bbs.binmt.cc/
        - name: 鸟哥的Linux私房菜
          description: 鸟哥的Linux私房菜
          url: http://cn.linux.vbird.org/
        - name: xda-developers
          description: 行动软体开发社群
          url: https://www.xda-developers.com/
        - name: V2EX
          description: 技术论坛，创意工作者们的社区
          url: https://www.v2ex.com/
        - name: 需要我帮你百度一下吗
          description: 需要我帮你百度一下吗生成器
          url: https://gsyx666.github.io/lmbdfy.html
    - name: 导航网站
      sites:
        - name: eryajf 导航
          description: eryajf 导航
          url: http://nav.eryajf.net/
    - name: 技术工具
      sites:
        - name: misaka ping
          description: 多点 Ping 工具
          url: https://ping.sx/ping
        - name: JSON Editor Online
          description: JSON 工具，可以对比两个 JSON，以及分享 JSON 片段
          url: https://jsoneditoronline.org/
        - name: Excalidraw
          description: 流程图工具，可以画手写风格的图表
          url: https://excalidraw.com/
        - name: ip.sb
          description: IP 获取
          url: https://ip.sb/
    - name: 论坛社区
      sites:
        - name: 虎扑步行街
          description: 虎扑步行街热门话题，每日话题
          url: https://bbs.hupu.com/all-gambia
        - name: V2EX
          description: 技术论坛，创意工作者们的社区
          url: https://www.v2ex.com/
        - name: GitHub Trending
          description: GitHub 排行榜
          url: https://github.com/trending  
        - name: Lobsters
          description: 技术论坛
          url: https://lobste.rs/
        - name: 热门微博
          description: 热门微博，微博热搜
          url: https://weibo.com/hot
        - name: Reddit Rust 频道
          description: Reddit Rust 专区
          url: https://www.reddit.com/r/rust/
        - name: Youtube
          description: 全球最大的学习分享平台
          url: https://www.youtube.com/
        - name: Google
          description: 全球最大的UI学习分享平台
          url: https://www.google.com/
        - name: Medium
          description: Read, write and share stories that matter
          url: https://medium.com/
    - name: 社区资讯
      sites:
        - name: 雷锋网
          description: 人工智能和智能硬件领域的互联网科技媒体
          url: https://www.leiphone.com/
        - name: 36kr
          description: 创业资讯、科技新闻
          url: http://36kr.com/
        - name: 数英网
          description: 数字媒体及职业招聘网站
          url: https://www.digitaling.com/
        - name: 猎云网
          description: 互联网创业项目推荐和创业创新资讯
          url: http://www.lieyunwang.com/
        - name: 人人都是产品经理
          description: 产品经理、产品爱好者学习交流平台
          url: http://www.woshipm.com/
        - name: 互联网早读课
          description: 互联网行业深度阅读与学习平台
          url: https://www.zaodula.com/
        - name: 产品壹佰
          description: 为产品经理爱好者提供最优质的产品资讯、原创内容和相关视频课程
          url: http://www.chanpin100.com/
        - name: PMCAFF
          description: 中国第一产品经理人气组织，专注于研究互联网产品
          url: http://www.pmcaff.com/
        - name: 爱运营
          description: 网站运营人员学习交流，专注于网站产品运营管理、淘宝运营。
          url: http://www.iyunying.org/
        - name: 鸟哥笔记
          description: 移动互联网第一干货平台
          url: http://www.niaogebiji.com/
        - name: 古田路9号
          description: 国内专业品牌创意平台
          url: http://www.gtn9.com/
        - name: 优阁网
          description: UI设计师学习交流社区
          url: http://www.uigreat.com/
    - name: 发现产品
      sites:
        - name: NEXT
          description: 不错过任何一个新产品
          url: http://next.36kr.com/posts
        - name: 少数派
          description: 高品质数字消费指南
          url: https://sspai.com/
        - name: 利器
          description: 创造者和他们的工具
          url: http://liqi.io/
        - name: Today
          description: 为身边的新产品喝彩
          url: http://today.itjuzi.com/
        - name: 小众软件
          description: 在这里发现更多有趣的应用
          url: https://faxian.appinn.com/
        - name: Pttrns
          description: Check out the finest collection of design patterns, resources, mobile apps and inspiration
          url: https://www.pttrns.com/
        - name: Collect UI
          description: Daily inspiration collected from daily ui archive and beyond.
          url: http://collectui.com/
        - name: UI uigreat
          description: APP界面截图参考
          url: http://ui.uigreat.com/
    - name: 图标素材
      sites:
        - name: Iconfinder
          description: 2,100,000+ free and premium vector icons.
          url: https://www.iconfinder.com
        - name: iconfont
          description: 阿里巴巴矢量图标库
          url: http://www.iconfont.cn/
        - name: iconmonstr
          description: Free simple icons for your next project
          url: https://iconmonstr.com/
        - name: Icon Archive
          description: Search 590,912 free icons
          url: http://www.iconarchive.com/
        - name: FindIcons
          description: Search through 300,000 free icons
          url: https://findicons.com/
        - name: IcoMoonApp
          description: Icon Font, SVG, PDF & PNG Generator
          url: https://icomoon.io/app/
        - name: easyicon
          description: PNG、ICO、ICNS格式图标搜索、图标下载服务
          url: http://www.easyicon.net/
        - name: flaticon
          description: 634,000+ Free vector icons in SVG, PSD, PNG, EPS format or as ICON FONT.
          url: https://www.flaticon.com/
        - name: UICloud
          description: The largest user interface design database in the world.
          url: http://ui-cloud.com/
        - name: Material icons
          description: Access over 900 material system icons, available in a variety of sizes and densities, and as a web font.
          url: https://material.io/icons/
        - name: Font Awesome Icon
          description: The complete set of 675 icons in Font Awesome
          url: fontawesomeicon
        - name: ion icons
          description: The premium icon font for Ionic Framework.
          url: http://ionicons.com/
        - name: Simpleline Icons
          description: Simple line Icons pack
          url: http://simplelineicons.com/
    - name: LOGO设计
      sites:
        - name: Iconsfeed
          description: iOS icons gallery
          url: http://www.iconsfeed.com/
        - name: iOS Icon Gallery
          description: Showcasing beautiful icon designs from the iOS App Store
          url: http://iosicongallery.com/
        - name: World Vector Logo
          description: Brand logos free to download
          url: https://worldvectorlogo.com/
        - name: Instant Logo Search
          description: Search & download thousands of logos instantly
          url: http://instantlogosearch.com/
    - name: 学习资源
      sites:
        - name: Leetcode
          description: 面试准备算法题必备，国内站和国外站数据互通
          url: https://leetcode-cn.com/
        - name: CodeTop
          description: 企业面试题库
          url: https://codetop.cc/#/home
        - name: "6.824"
          description: 著名的分布式课程
          url: https://pdos.csail.mit.edu/6.824/index.html
        - name: Talent Plan
          description: Pincap 的开源学习计划，类似 6.824 课程
          url: https://github.com/pingcap/talent-plan
        - name: 黄简艺术工作室
          description: 很完善的一套书法教程
          url: http://www.chinese-artists.net/huangjian/lessons/index.html
        - name: 菜鸟教程
          description: 入门教程合集
          url: https://www.runoob.com/
    - name: PPT资源
      sites:
        - name: OfficePLUS
          description: OfficePLUS，微软Office官方在线模板网站！
          url: http://www.officeplus.cn/Template/Home.shtml
        - name: 优品PPT
          description: 高质量的模版，而且还有PPT图表，PPT背景图等资源
          url: http://www.ypppt.com/
        - name: PPT+
          description: PPT加直播、录制和分享—PPT+语音内容分享平台
          url: http://www.pptplus.cn/
        - name: PPTMind
          description: 分享高端ppt模板与keynote模板的数字作品交易平台
          url: http://www.pptmind.com/
        - name: tretars
          description: The best free Mockups from the Web
          url: http://www.tretars.com/ppt-templates
        - name: 5百丁
          description: 中国领先的PPT模板共享平台
          url: http://ppt.500d.me/
    - name: UED团队
      sites:
        - name: Airbnb Design
          description: Airbnb Design
          url: https://airbnb.design
        - name: Facebook Design
          description: Facebook Design
          url: http://facebook.design/
        - name: Google Design
          description: Google Design
          url: https://design.google/
        - name: eico design
          description: 数字化咨询与产品专家
          url: http://eicodesign.com/
        - name: nice design
          description: nicedesign奈思设计是领先的用户体验设计与互联网品牌建设公司
          url: http://www.niceui.cn/
        - name: 腾讯CDC
          description: 腾讯CDC关注于互联网视觉设计、交互设计、用户研究、前端开发。
          url: http://cdc.tencent.com/
        - name: TGideas
          description: TGideas隶属于腾讯公司互动娱乐业务系统的专业推广类设计团队
          url: http://tgideas.qq.com/
        - name: ISUX
          description: 腾讯社交用户体验设计部
          url: https://isux.tencent.com/
        - name: MXD
          description: 腾讯MIG无线互联网事业群设计团队
          url: http://mxd.tencent.com/
        - name: Aliued
          description: 阿里巴巴国际UED团队
          url: http://www.aliued.com/
        - name: U一点
          description: 阿里巴巴（中国站）用户体验设计部博客U一点设计 UED团队
          url: http://www.aliued.cn/
        - name: 网易uedc
          description: 网易用户体验设计中心（User Experience Design Center）
          url: http://uedc.163.com/
        - name: 百度用户体验中心
          description: 百度用户体验中心
          url: http://ued.baidu.com/
        - name: 京东设计中心
          description: 京东设计中心
          url: http://jdc.jd.com/
        - name: 百度企业产品用户体验中心
          description: 百度企业产品用户体验中心
          url: http://eux.baidu.com/
        - name: 携程设计委员会
          description: 携程设计委员会-Ctrip Design Committee
          url: http://ued.ctrip.com/
